/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class Question10 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Question10
     */
    public Question10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Joption1 = new javax.swing.JRadioButton();
        Joption2 = new javax.swing.JRadioButton();
        Joption4 = new javax.swing.JRadioButton();
        Joption3 = new javax.swing.JRadioButton();
        Jsubmit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("What is the best way to have a data and the slide number appear on every slide?");

        Joption1.setBackground(new java.awt.Color(153, 255, 153));
        Joption1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Joption1.setForeground(new java.awt.Color(255, 0, 0));
        Joption1.setText(" chooses Tools, Header and Footer, click Slide tab, select the desired options, and click Apply to All.");

        Joption2.setBackground(new java.awt.Color(153, 255, 153));
        Joption2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Joption2.setForeground(new java.awt.Color(255, 0, 0));
        Joption2.setText("chooses Insert, Header and Footer, click Slide tab, select the desired options, and click Apply to All.");
        Joption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Joption2ActionPerformed(evt);
            }
        });

        Joption4.setBackground(new java.awt.Color(153, 255, 153));
        Joption4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Joption4.setForeground(new java.awt.Color(255, 0, 0));
        Joption4.setText("chooses File, Header and Footer, click Slide tab, select the desired options, and click Apply to All.");
        Joption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Joption4ActionPerformed(evt);
            }
        });

        Joption3.setBackground(new java.awt.Color(153, 255, 153));
        Joption3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Joption3.setForeground(new java.awt.Color(255, 0, 0));
        Joption3.setText(" chooses View, Header and Footer, click Slide tab, select the desired options, and click Apply to All.");
        Joption3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Joption3ActionPerformed(evt);
            }
        });

        Jsubmit.setText("Submit");
        Jsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(Joption1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Joption2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Joption4, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Joption3, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(Jsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Joption1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Joption2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(Joption3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Joption4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Jsubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Joption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Joption4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Joption4ActionPerformed

    private void Joption3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Joption3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Joption3ActionPerformed

    private void Joption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Joption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Joption2ActionPerformed

    private void JsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsubmitActionPerformed
       if(Joption2.isSelected() )
                       {
                           QuestionSet.marks ++;
                           if(Joption4.isSelected() || Joption3.isSelected()|| Joption1.isSelected()) 
                                   {
                                       QuestionSet.marks--;
                                   }
                       }
        else if(Joption4.isSelected() || Joption3.isSelected()|| Joption1.isSelected() )
        {
            QuestionSet.count++;
        }
        
                else
                    QuestionSet.unanswered ++;
        
        System.out.println(QuestionSet.count);
                System.out.println(QuestionSet.marks);
                        System.out.println(QuestionSet.unanswered);
                        if(Jsubmit.getActionCommand().equals("Submit")) 
        {
            setVisible(false);
        }
    }//GEN-LAST:event_JsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Joption1;
    private javax.swing.JRadioButton Joption2;
    private javax.swing.JRadioButton Joption3;
    private javax.swing.JRadioButton Joption4;
    private javax.swing.JButton Jsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
